---
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languageCode: en-us
languageName: English

baseUrl: https://stcentral-hub.github.io.git
title: STC Hub

sectionPagesMenu: main
enableGitInfo: true

taxonomies:
  author: authors
  category: categories
  tag: tags


languages:
  en:
    languageName: English
    weight: 501
  fr:
    languageName: Français
    weight: 502
  es:
    languageName: Español
    weight: 503
  de:
    languageName: Deutsch
    weight: 504
  it:
    languageName: Italiano
    weight: 505
  pt:
    languageName: Português
    weight: 506
  ru:
    languageName: русский
    weight: 507
  tk:
    languageName: Türkçe
    weight: 508
  zh:
    languageName: 中文
    weight: 509
  zh_tr:
    languageName: 漢語
    weight: 510
  ja:
    languageName: 日本語
    weight: 511
  ko:
    languageName: 한국어
    weight: 512
  uk:
    languageName: украї́нська
    weight: 513
