---
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languageCode: en-us
languageName: English

baseUrl: https://example.com
title: STC Hub

sectionPagesMenu: main
enableGitInfo: true
