---
main:
  - identifier: home
    name: Home
    url: /
    weight: 101
  - identifier: stc
    name: ST Central
    url: https://st-central.net/
    weight: 201
  - identifier: articles
    name: Articles
    url: /articles/
    weight: 301
