---
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

baseUrl: https://example.com
languageCode: en-us
languageName: English
title: Shop Titans Metadata Service

sectionPagesMenu: main